### ISSUE TITLE
Galaxy A5 SM-A500FU Firmware Download and How to Install

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#11]
Galaxy A5 SM-A500FU Firmware Download and How to Install<br>
http://androidromupdate.com/galaxy-a5-sm-a500fu-firmware-download/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/galaxy-a5-sm-a500fu-firmware-download/">Galaxy A5 SM-A500FU Firmware Download and How to Install</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">Android ROM Update</a>.</p>
<p>Here you can download the&nbsp;Samsung Galaxy A5 SM-A500FU firmware and manually install it unto the device. The Galaxy A5 A500FU is one of the first gen of the Galaxy A5 released in 2014. This device was originally runs in Android 4.4.4 KitKat Out of the box. While over the course &hellip;</p>
<br><br>
via Android ROM Update http://androidromupdate.com<br>
February 15, 2017 at 10:44AM

**Comment by 0xbadshah** [comment]
Samsung Galaxy A5 was already inserted into the list by @mimi89999 . Updated the list with the image, committed and merged into the master branch. Commit a2a6c186fdba6edbdb3dac7c8aa708c832cd48f5
