### ISSUE TITLE
Official Nougat G930TUVU4BQB1 Firmware for T-Mobile Galaxy S7 SM-G930T

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#12]
Official Nougat G930TUVU4BQB1 Firmware for T-Mobile Galaxy S7 SM-G930T<br>
http://androidromupdate.com/official-nougat-g930tuvu4bqb1-firmware-tmobile-galaxy-s7-sm-g930t/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/official-nougat-g930tuvu4bqb1-firmware-tmobile-galaxy-s7-sm-g930t/">Official Nougat G930TUVU4BQB1 Firmware for T-Mobile Galaxy S7 SM-G930T</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">Android ROM Update</a>.</p>
<p>T-Mobile Samsung Galaxy S7 has finally received the official Android Nougat update. The first Nougat OS version dubbed as&nbsp;G930TUVU4BQB1 is seeding out via over the air. &nbsp;Those who did not modify their device can simply grab the this update, while those who have a modified or rooted devices may only &hellip;</p>
<br><br>
via Android ROM Update http://androidromupdate.com<br>
February 18, 2017 at 07:42AM

**Comment by 0xbadshah** [comment]
**Commit :** 1ff62ce
