### ISSUE TITLE
Official Nougat G935TUVU4BQB1 Firmware for T-Mobile Galaxy S7 edge SM-G935T

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#13]
Official Nougat G935TUVU4BQB1 Firmware for T-Mobile Galaxy S7 edge SM-G935T<br>
http://androidromupdate.com/official-nougat-g935tuvu4bqb1-firmware-t-mobile-galaxy-s7-edge-sm-g935t/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/official-nougat-g935tuvu4bqb1-firmware-t-mobile-galaxy-s7-edge-sm-g935t/">Official Nougat G935TUVU4BQB1 Firmware for T-Mobile Galaxy S7 edge SM-G935T</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">Android ROM Update</a>.</p>
<p>T-Mobile Samsung Galaxy S7 and S7 edge has finally received the official Android Nougat update. For the Galaxy S7 SM-G930T the Nougat update came out as&nbsp;G930TUVU4BQB1. While the Galaxy S7 edge got the build version G935TUVU4BQB1. For those hose who did not modify their device can simply grab the this &hellip;</p>
<br><br>
via Android ROM Update http://androidromupdate.com<br>
February 18, 2017 at 08:26AM

**Comment by 0xbadshah** [comment]
**Commit :** ce221a0c
