### ISSUE TITLE
Install G935AUCU4BQA6 Nougat Update on Galaxy S7 edge SM-G935A (AT&T)

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#17]
Install G935AUCU4BQA6 Nougat Update on Galaxy S7 edge SM-G935A (AT&amp;T)<br>
http://androidromupdate.com/install-g935aucu4bqa6-nougat-update-galaxy-s7-edge-sm-g935a-att/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/install-g935aucu4bqa6-nougat-update-galaxy-s7-edge-sm-g935a-att/">Install G935AUCU4BQA6 Nougat Update on Galaxy S7 edge SM-G935A (AT&amp;T)</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">Android ROM Update</a>.</p>
<p>If somehow you cannot upgrade your AT&amp;T Galaxy S7 edge SM-G935A to the official Android 7.0 Nougat Update G935AUCU4BQA6 via Over-The-Air then&nbsp;this guide is made out for you. &nbsp;The best way for you to get the Nougat update on your device is to sideload the stock G935AUCU4BQA6 either via ADB &hellip;</p>
<br><br>
via Android ROM Update http://androidromupdate.com<br>
February 27, 2017 at 02:13AM

**Comment by 0xbadshah** [comment]
Galaxy S7 Edge already in the list.
