### ISSUE TITLE
G930AUCU4BQA6 Nougat Firmware Install on AT&T Galaxy S7 SM-G930A

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#18]
G930AUCU4BQA6 Nougat Firmware Install on AT&amp;T Galaxy S7 SM-G930A<br>
http://androidromupdate.com/g930aucu4bqa6-nougat-firmware-install-on-att-galaxy-s7-sm-g930a/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/g930aucu4bqa6-nougat-firmware-install-on-att-galaxy-s7-sm-g930a/">G930AUCU4BQA6 Nougat Firmware Install on AT&amp;T Galaxy S7 SM-G930A</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">Android ROM Update</a>.</p>
<p>Upgrade your AT&amp;T Galaxy S7 SM-G930A to the official Android 7.0 Nougat Update G930AUCU4BQA6&nbsp;if somehow you cannot get the update via Over-The-Air. To get the Nougat update just simply sideload the&nbsp;G930AUCU4BQA6&nbsp;stock firmware either via ADB or right thru the SD-card update in Recovery mode. Android version: 7.0 Baseband version: G930AUCU4BQA6 &hellip;</p>
<br><br>
via Android ROM Update http://androidromupdate.com<br>
February 27, 2017 at 10:49PM

**Comment by 0xbadshah** [comment]
Updated ! Commit :  fbff039
