### ISSUE TITLE
February security update starts hitting Samsung Galaxy S7/S7 edge in India

### ISSUE THREAD

**Issue by c0dist** [AndroidTamer/KnowledgeBase#19]
http://gsmarena.com/february_security_update_starts_hitting_samsung_galaxy_s7_s7_edge_in_india-news-23594.php

I have not received the notification on my S7 Edge yet. But the article mentions S7 explicitly and guesses about S7 Edge.

> While there's no confirmation on whether the Galaxy S7 edge is also receiving the latest security patch, we don't see any reason why that won't be the case. This update comes shortly after the Galaxy S6 started receiving the February update in the country.

**Comment by anantshri** [comment]
Lets right now only mark S7 coz we have evidence in form of image source from this article. But lets not mark s7 edge till we get a confirmation from user or a media post confirming updates available.

**Comment by anantshri** [comment]
details already added now.
