### ISSUE TITLE
G935PVPU4BQAA Nougat Firmware Sprint Galaxy S7 edge SM-G935P

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#21]
G935PVPU4BQAA Nougat Firmware Sprint Galaxy S7 edge SM-G935P<br>
http://androidromupdate.com/g935pvpu4bqaa-nougat-firmware-sprint-galaxy-s7-edge-sm-g935p/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/g935pvpu4bqaa-nougat-firmware-sprint-galaxy-s7-edge-sm-g935p/">G935PVPU4BQAA Nougat Firmware Sprint Galaxy S7 edge SM-G935P</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">Android Firmware Updates</a>.</p>
<p>For those who&nbsp;might have some&nbsp;difficulties to upgrade their&nbsp;Sprint Samsung Galaxy S7 edge SM-G935P to official Android 7.0 Nougat firmware version G935PVPU4BQAA via Over-The-Air, then this is for you. &nbsp;You might could probably, your device has been rooted or modified, or your outside in the US territories to get the said &hellip;</p>
<br><br>
via Android Firmware Updates http://androidromupdate.com<br>
March 11, 2017 at 06:26PM

**Comment by 0xbadshah** [comment]
Updated. Commit: 21fb88b
