### ISSUE TITLE
G935VVRU4BQA2 Android 7.0 Nougat Verizon Galaxy S7 edge SM-G935V Firmware

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#24]
G935VVRU4BQA2 Android 7.0 Nougat Verizon Galaxy S7 edge SM-G935V Firmware<br>
http://androidromupdate.com/g935vvru4bqa2-android-7-0-nougat-verizon-galaxy-s7-edge-sm-g935v-firmware/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/g935vvru4bqa2-android-7-0-nougat-verizon-galaxy-s7-edge-sm-g935v-firmware/">G935VVRU4BQA2 Android 7.0 Nougat Verizon Galaxy S7 edge SM-G935V Firmware</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">Android Firmware Updates</a>.</p>
<p>Android 7.0 Nougat firmware G935VVRU4BQA2 for Verizon Galaxy S7 edge SM-G935V. The latter is the first official Nougat update released on Verizon Galaxy S7 edge. The stock firmware is only for those who did not managed&nbsp;to get update vai Over-The-Air OTA. So just in-case you might&nbsp;want the stock firmware itself, &hellip;</p>
<br><br>
via Android Firmware Updates http://androidromupdate.com<br>
March 19, 2017 at 03:47AM

**Comment by 0xbadshah** [comment]
Updated ! Commit: 1a7285d
