### ISSUE TITLE
Install G925FXXU5EQAC UK Official Android 7.0 Nougat Firmware Galaxy S6 edge SM-G925F Unlocked Variants

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#27]
Install G925FXXU5EQAC UK Official Android 7.0 Nougat Firmware Galaxy S6 edge SM-G925F Unlocked Variants<br>
http://androidromupdate.com/g925fxxu5eqac-uk-official-android-7-0-nougat-firmware-galaxy-s6-edge-sm-g925f-unlocked-variants/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/g925fxxu5eqac-uk-official-android-7-0-nougat-firmware-galaxy-s6-edge-sm-g925f-unlocked-variants/">Install G925FXXU5EQAC UK Official Android 7.0 Nougat Firmware Galaxy S6 edge SM-G925F Unlocked Variants</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">Android Firmware Updates</a>.</p>
<p>The official Android 7.0 Nougat updates is hitting the Samsung Galaxy S6 edge SM-G925F unlocked variants to which came out as firmware version&nbsp;G925FXXU5EQAC.&nbsp;However, the roll out only happens in&nbsp;the United Kingdom and Ireland at of this moment, while other countries may still hold on for a while until the massive&nbsp;roll &hellip;</p>
<br><br>
via Android Firmware Updates http://androidromupdate.com<br>
March 23, 2017 at 12:05AM

**Comment by 0xbadshah** [comment]
Security status date not found in image, but mentioned in blog post.
Updated ! Commit : 27bbd09
