### ISSUE TITLE
Install N920CXXU3CQC7 Official Android 7.0 Nougat on Galaxy Note 5 SM-N920C

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#28]
Install N920CXXU3CQC7 Official Android 7.0 Nougat on Galaxy Note 5 SM-N920C<br>
http://androidromupdate.com/install-n920cxxu3cqc7-official-android-7-0-nougat-on-galaxy-note-5-sm-n920c/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/install-n920cxxu3cqc7-official-android-7-0-nougat-on-galaxy-note-5-sm-n920c/">Install N920CXXU3CQC7 Official Android 7.0 Nougat on Galaxy Note 5 SM-N920C</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">Android Firmware Updates</a>.</p>
<p>Samsung has started pushing the Galaxy Note 5 SM-N920C official Android 7.0 Nougat upgrades. The updates were officially rolled out in the Middle East region. For those who might not been able to get the said Android 7.0 Nougat update at the right time, here goes the stock&nbsp;firmware version N920CXXU3CQC7&nbsp;itself. &hellip;</p>
<br><br>
via Android Firmware Updates http://androidromupdate.com<br>
March 24, 2017 at 07:17AM

**Comment by 0xbadshah** [comment]
Updated. Commit: 07069fc
