### ISSUE TITLE
A300FXXU1BQB2 Galaxy A3 A300F March 2017 Firmware Updates

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#30]
A300FXXU1BQB2 Galaxy A3 A300F March 2017 Firmware Updates<br>
http://androidromupdate.com/a300fxxu1bqb2-galaxy-a3-a300f-march-2017-firmware-updates/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/a300fxxu1bqb2-galaxy-a3-a300f-march-2017-firmware-updates/">A300FXXU1BQB2 Galaxy A3 A300F March 2017 Firmware Updates</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">Android Firmware Updates</a>.</p>
<p>New Update firmware version A300FXXU1BQB2 for Galaxy A3 SM-A300F, of which freshly released&nbsp;as of March 2017. This update includes the February&nbsp;1, 2017 Android security patch level, bug-fixes, and improvements to the device performance. It is officially rolled out by Samsung in select European countries. The&nbsp;A300FXXU1BQB2 is an update to the</p>
<br><br>
via Android Firmware Updates http://androidromupdate.com<br>
March 30, 2017 at 12:36AM

**Comment by 0xbadshah** [comment]
Firmware updates not included ! No image as well.
