### ISSUE TITLE
N7100XXSFQA1 Galaxy Note II GT-N7100 March 2017 Firmware Updates

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#31]
N7100XXSFQA1 Galaxy Note II GT-N7100 March 2017 Firmware Updates<br>
http://androidromupdate.com/n7100xxsfqa1-galaxy-note-ii-gt-n7100-march-2017-firmware-updates/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/n7100xxsfqa1-galaxy-note-ii-gt-n7100-march-2017-firmware-updates/">N7100XXSFQA1 Galaxy Note II GT-N7100 March 2017 Firmware Updates</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">Android Firmware Updates</a>.</p>
<p>To those who still rocking the Galaxy Note II GT-N7100 until this year. &nbsp;Yes folks! We knew that this device hasn&rsquo;t received an update for a quite some time now, it&rsquo;s because it cannot be denied that this device is considered as the&nbsp;grandfather of the &nbsp;Galaxy Note 4 and Galaxy</p>
<br><br>
via Android Firmware Updates http://androidromupdate.com<br>
April 01, 2017 at 02:05AM

**Comment by 0xbadshah** [comment]
Firmware updates not included ! No image as well.
