### ISSUE TITLE
N920PVPU3DQC5 Sprint Galaxy Note 5 SM-N920P Android 7.0 Nougat Stock Firmware

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#34]
N920PVPU3DQC5 Sprint Galaxy Note 5 SM-N920P Android 7.0 Nougat Stock Firmware<br>
http://androidromupdate.com/n920pvpu3dqc5-sprint-galaxy-note-5-sm-n920p-android-7-0-nougat-stock-firmware/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/n920pvpu3dqc5-sprint-galaxy-note-5-sm-n920p-android-7-0-nougat-stock-firmware/">N920PVPU3DQC5 Sprint Galaxy Note 5 SM-N920P Android 7.0 Nougat Stock Firmware</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">Android Firmware Updates</a>.</p>
<p>Sprint Galaxy Note 5 (SM-N920P) official Android 7.0 Nougat update firmware version N920PVPU3DQC5. This is the&nbsp;first build came around and were officially released via Over-The-Air (OTA) on April 5, 2017. However, if your device have been modified you might have missed this update. As long as your phone is rooted</p>
<br><br>
via Android Firmware Updates http://androidromupdate.com<br>
April 16, 2017 at 06:32AM

**Comment by 0xbadshah** [comment]
Added. Commit: 44703e1
