### ISSUE TITLE
G928TUVU4DQC2 T-Mobile Galaxy S6 edge SM-G928T April 2017 Firmware Update

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#43]
G928TUVU4DQC2 T-Mobile Galaxy S6 edge+ SM-G928T April 2017 Firmware Update<br>
http://androidromupdate.com/g928tuvu4dqc2-t-mobile-galaxy-s6-edge-sm-g928t-april-2017-firmware-update/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/g928tuvu4dqc2-t-mobile-galaxy-s6-edge-sm-g928t-april-2017-firmware-update/">G928TUVU4DQC2 T-Mobile Galaxy S6 edge+ SM-G928T April 2017 Firmware Update</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">Android Firmware Updates</a>.</p>
<p>Firmware build G928TUVU4DQC2 for T-Mobile Galaxy S6 Edge+ SM-G928T. The G928TUVU4DQC2 is based Android 6.0.1 Marshmallow, but it brings an&nbsp;updated&nbsp;Android security fixes. Galaxy S6 edge+ SM-G928T Firmware version G928TUVU4DQC2 Device Galaxy S6 edge+ SM-G928T Android version 6.0.1 Marshmallow Android security patch level January 1, 2017 Baseband version G928TUVU4DQC2 Kernel version</p>
<br><br>
via Android Firmware Updates http://androidromupdate.com<br>
April 21, 2017 at 12:28AM

**Comment by 0xbadshah** [comment]
No image source !
