### ISSUE TITLE
G928AUCU4EQC6 AT&T Galaxy S6 Edge Android 7.0 Nougat ADB/Odin Stock Firmware

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#45]
G928AUCU4EQC6 AT&amp;T Galaxy S6 Edge+ Android 7.0 Nougat ADB/Odin Stock Firmware<br>
http://androidromupdate.com/g928aucu4eqc6-att-galaxy-s6-edge-android-7-0-nougat-adbodin-stock-firmware/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/g928aucu4eqc6-att-galaxy-s6-edge-android-7-0-nougat-adbodin-stock-firmware/">G928AUCU4EQC6 AT&amp;T Galaxy S6 Edge+ Android 7.0 Nougat ADB/Odin Stock Firmware</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">AndroidROMupdate</a>.</p>
<p>AT&amp;T Galaxy S6 Edge+ SM-G928A Stock Firmware version G928AUCU4EQC6. This is the first official Android 7.0 Nougat update released to the latter. Galaxy S6 edge+ SM-G928A Firmware version G928AUCU4EQC6 Device Galaxy S6 edge+ SM-G928A Android version&nbsp;7.0 (Nougat) Android security patch level March 1, 2017 Baseband version G928AUCU4EQC6 Kernel version 3.10.61-10809541</p>
<br><br>
via AndroidROMupdate http://androidromupdate.com<br>
April 23, 2017 at 12:33AM

**Comment by 0xbadshah** [comment]
No image source !
