### ISSUE TITLE
G928W8VLU4CQC8 Galaxy S6 edge SM-G928W8 Canadian Users Android 7.0 Nougat Firmware

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#46]
G928W8VLU4CQC8 Galaxy S6 edge+ SM-G928W8 Canadian Users Android 7.0 Nougat Firmware<br>
http://androidromupdate.com/g928w8vlu4cqc8-galaxy-s6-edge-sm-g928w8-canadian-users-android-7-0-nougat-firmware/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/g928w8vlu4cqc8-galaxy-s6-edge-sm-g928w8-canadian-users-android-7-0-nougat-firmware/">G928W8VLU4CQC8 Galaxy S6 edge+ SM-G928W8 Canadian Users Android 7.0 Nougat Firmware</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">AndroidROMupdate</a>.</p>
<p>Official Android 7.0 Nougat upgrade firmware version G928W8VLU4CQC8 for Canadian users of the Galaxy S6 edge+, the SM-G928W8 variant. This is the first official Nougat released build of which exclusively rolled out in Canada only. If you might have missed this update or either you might have a rooted and</p>
<br><br>
via AndroidROMupdate http://androidromupdate.com<br>
April 25, 2017 at 02:42AM

**Comment by 0xbadshah** [comment]
No Patch date !
