### ISSUE TITLE
N915TUVU2DQC1 T-Mobile Galaxy Note Edge N915T Firmware

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#47]
N915TUVU2DQC1 T-Mobile Galaxy Note Edge N915T Firmware<br>
http://androidromupdate.com/n915tuvu2dqc1-t-mobile-galaxy-note-edge-firmware/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/n915tuvu2dqc1-t-mobile-galaxy-note-edge-firmware/">N915TUVU2DQC1 T-Mobile Galaxy Note Edge N915T Firmware</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">AndroidROMupdate</a>.</p>
<p>A firmware update for T-Mobile Galaxy Note edge SM-N915T to version N915TUVU2DQC1. The latter brings some new features and various system improvements&nbsp;and the March 1, 2017 Android security update. The build is still base in Android 6.0.1 Marshmallow. What&rsquo;s New: March 1, 2017 Android security patches Added video call, Samsung</p>
<br><br>
via AndroidROMupdate http://androidromupdate.com<br>
April 25, 2017 at 11:27PM

**Comment by 0xbadshah** [comment]
No image source !
