### ISSUE TITLE
N920VVRU3CQB9 Verizon Galaxy Note 5 N920V Android 7.0 Nougat Firmware Update

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#53]
N920VVRU3CQB9 Verizon Galaxy Note 5 N920V Android 7.0 Nougat Firmware Update<br>
http://androidromupdate.com/n920vvru3cqb9-verizon-galaxy-note-5-n920v-android-7-0-nougat-firmware-update/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/n920vvru3cqb9-verizon-galaxy-note-5-n920v-android-7-0-nougat-firmware-update/">N920VVRU3CQB9 Verizon Galaxy Note 5 N920V Android 7.0 Nougat Firmware Update</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">AndroidROMupdate</a>.</p>
<p>Verizon Galaxy Note 5 N920V Android 7.0 Nougat Firmware Update version N920VVRU3CQB9. This is the first official Android 7.0 Nougat released build. Along with Android 7.0 Nougat goodies, it also brings the March 1, 2017 Android security patch level. Firmware version details: Device: Galaxy Note 5 SM-N920V (Verizon) Android version:</p>
<br><br>
via AndroidROMupdate http://androidromupdate.com<br>
April 28, 2017 at 12:34AM

**Comment by 0xbadshah** [comment]
No patch status
