### ISSUE TITLE
N920CXXU3CQD1 Galaxy Note5 SM-N920C Android 7.0 Nougat with April 2017 Security Update

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#64]
N920CXXU3CQD1 Galaxy Note5 SM-N920C Android 7.0 Nougat with April 2017 Security Update<br>
http://androidromupdate.com/n920cxxu3cqd1-galaxy-note5-sm-n920c-android-7-0-nougat-with-april-2017-security-update/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/n920cxxu3cqd1-galaxy-note5-sm-n920c-android-7-0-nougat-with-april-2017-security-update/">N920CXXU3CQD1 Galaxy Note5 SM-N920C Android 7.0 Nougat with April 2017 Security Update</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">AndroidROMupdate</a>.</p>
<p>The Galaxy Note 5 SM-N920C has gotten an update to version N920CXXU3CQD1. It is another round of Android 7.0 Nougat update but includes the April 2017 Android security patches. Device: Galaxy Note5 Model number: SM-N920C Android version: 7.0 (Nougat) Android security patch level: April&nbsp;1, 2017 Baseband version: N920CXXU3QC3 Kernel version:</p>
<br><br>
via AndroidROMupdate http://androidromupdate.com<br>
May 03, 2017 at 04:00AM

**Comment by 0xbadshah** [comment]
No patch date image
