### ISSUE TITLE
N920AUCS4EQD1 Android 7.0 Nougat Firmware with April Security Patch Update for AT&T Galaxy Note5

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#65]
N920AUCS4EQD1 Android 7.0 Nougat Firmware with April Security Patch Update for AT&amp;T Galaxy Note5<br>
http://androidromupdate.com/n920aucs4eqd1-android-7-0-nougat-firmware-with-april-security-patch-update-for-att-galaxy-note5/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/n920aucs4eqd1-android-7-0-nougat-firmware-with-april-security-patch-update-for-att-galaxy-note5/">N920AUCS4EQD1 Android 7.0 Nougat Firmware with April Security Patch Update for AT&amp;T Galaxy Note5</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">AndroidROMupdate</a>.</p>
<p>AT&amp;T Galaxy Note 5 SM-N920A Android 7.0 Nougat Firmware update version N920AUCS4EQD1. This version includes April 1, 2017 Android Security Patch Level. Device name: SAMSUNG-SM-N920A (AT&amp;T) Android version: 7.0 (Nougat) Android Security patch level: April1, 2017 Baseband version: N920AUCS4EQD1 Kernel version: 3.10.61-10809541 Build number: NRD90M.N920AUCS4EQD1 CP N920AUCS4EQD1 CP N920AUCS4EQD1 CSC</p>
<br><br>
via AndroidROMupdate http://androidromupdate.com<br>
May 04, 2017 at 04:15AM

**Comment by 0xbadshah** [comment]
Already in the list
