### ISSUE TITLE
G928TUVU4EQC6 Galaxy S6 edge SM-G928T T-Mobile Android 7.0 Nougat Stock Firmware

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#66]
G928TUVU4EQC6 Galaxy S6 edge+ SM-G928T T-Mobile Android 7.0 Nougat Stock Firmware<br>
http://androidromupdate.com/g928tuvu4eqc6-galaxy-s6-edge-plus-sm-g928t-t-mobile-android-7-0-nougat-stock-firmware/<br><p>The post <a rel="nofollow" href="http://androidromupdate.com/g928tuvu4eqc6-galaxy-s6-edge-plus-sm-g928t-t-mobile-android-7-0-nougat-stock-firmware/">G928TUVU4EQC6 Galaxy S6 edge+ SM-G928T T-Mobile Android 7.0 Nougat Stock Firmware</a> appeared first on <a rel="nofollow" href="http://androidromupdate.com">AndroidROMupdate</a>.</p>
<p>G928TUVU4EQC6 Official Android 7.0 Nougat firmware released on T-Mobile Galaxy S6 edge+ SM-G928T.&nbsp;Since this is the first Nougat released build, it simply means it can be rooted, and downgradeable. Yup, you can still downgrade from Android 7.0 Nougat G928TUVU4EQC6 back to Android 6.0.1 Marshmallow G928TUVS4DQA1 only, it didn&rsquo;t worked out</p>
<br><br>
via AndroidROMupdate http://androidromupdate.com<br>
May 07, 2017 at 03:50AM

**Comment by 0xbadshah** [comment]
Already in list
