### ISSUE TITLE
May security patch starts hitting Samsung Galaxy S7 edge

### ISSUE THREAD

**Issue by c0dist** [AndroidTamer/KnowledgeBase#67]
A new update is available for S7 Edge, which bumps up the Security Patch Level to "1 May 2017". As per the article linked below, 

> Currently, units with model number SM-G935FD are getting the update.

I can confirm that my phone (SM-G935FD) got the update today.

http://www.gsmarena.com/may_security_patch_starts_hitting_samsung_galaxy_s7_edge-news-25142.php

![screeshot](https://cloud.githubusercontent.com/assets/18549012/26304573/93febec8-3f09-11e7-9994-48e306b55676.jpg)

**Comment by 0xbadshah** [comment]
Thanks @c0dist. Updated !
