### ISSUE TITLE
An update source

### ISSUE THREAD

**Issue by anantshri** [AndroidTamer/KnowledgeBase#9]
This site seems to be tracking some phones, we should be putting the details with proper reference to them on our tracker for the devices being tracked http://androidromupdate.com

@Chan9390 would you be able to take this up. Lookup on the website if you find any specific details missing in our tracker add it and add reference to proper post.

**Comment by 0xbadshah** [comment]
The site consists of information about Samsung phones only.

**Comment by anantshri** [comment]
Thanks for adding the details. lets keep a track on the site for more update.

**Comment by anantshri** [comment]
Just a FYI I have added a IFTTT trigger on the RSS Feed so now blog post's should make an issue in this repository. 

Note: So far blog posts are for update rollout only. However if this situation changes we need to revisit the IFTTT logic.
